# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    CORENAME: hatari
    CORE_ARGS: -DENABLE_LIBRETRO=ON -DENABLE_HATARI=OFF -DENABLE_TOOLS=OFF -DENABLE_STATIC_ZLIB=ON -DENABLE_STATIC_CAPSIMAGE=ON
    EXTRA_PATH: src

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-cmake-mingw.yml'
    
  # Windows 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-mingw.yml'
    
  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'

  # Linux 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-i686.yml'

  # Linux 64-bit (ARM)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-aarch64.yml'

  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: 'osx-cmake-x86.yml'

  # MacOS arm64
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-cmake-arm64.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-cmake.yml'

  # iOS 9
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios9.yml'

  # iOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios-cmake.yml'

  # tvOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/tvos-cmake.yml'

  ################################## CONSOLES ################################
  # PlayStation Vita
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static-cmake.yml'

  # Nintendo Wii
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wii-static-cmake.yml'

  # Nintendo WiiU
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wiiu-static-cmake.yml'

  #################################### MISC ##################################
  # webOS 32-bit (LGTV)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/webos-cmake.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-cmake-x86_64
    - .core-defs
  variables:
    CORE_ARGS: -DENABLE_LIBRETRO=ON -DENABLE_HATARI=OFF -DENABLE_TOOLS=OFF -DENABLE_STATIC_ZLIB=ON -DENABLE_STATIC_CAPSIMAGE=OFF
    
# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-cmake-x86
    - .core-defs
  variables:
    CORE_ARGS: -DENABLE_LIBRETRO=ON -DENABLE_HATARI=OFF -DENABLE_TOOLS=OFF -DENABLE_STATIC_ZLIB=ON -DENABLE_STATIC_CAPSIMAGE=OFF

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-cmake-x86_64
    - .core-defs

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .libretro-linux-cmake-x86
    - .core-defs

# Linux 64-bit (ARM)
libretro-build-linux-aarch64:
  extends:
    - .libretro-linux-cmake-aarch64
    - .core-defs

# MacOS 64-bit
libretro-build-osx-x64:
  tags:
    - mac-apple-silicon
  extends:
    - .libretro-osx-cmake-x86_64
    - .core-defs
    
# MacOS arm64
libretro-build-osx-arm64:
  extends:
    - .libretro-osx-cmake-arm64
    - .core-defs
    
################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .libretro-android-cmake-armeabi-v7a
    - .core-defs

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-cmake-arm64-v8a
    - .core-defs

# Android 64-bit x86
android-x86_64:
  extends:
    - .libretro-android-cmake-x86_64
    - .core-defs

# Android 32-bit x86
android-x86:
  extends:
    - .libretro-android-cmake-x86
    - .core-defs

# iOS 9
libretro-build-ios9:
  extends:
    - .libretro-ios-cmake-ios9
    - .core-defs

# iOS
libretro-build-ios-arm64:
  extends:
    - .libretro-ios-cmake-arm64
    - .core-defs

# tvOS
libretro-build-tvos-arm64:
  extends:
    - .libretro-tvos-cmake-arm64
    - .core-defs

################################### CONSOLES #################################
# PlayStation Vita
libretro-build-vita:
  extends:
    - .libretro-vita-static-cmake-retroarch-master
    - .core-defs
  variables:
    CORE_ARGS: -DENABLE_LIBRETRO=ON -DENABLE_HATARI=OFF -DENABLE_TOOLS=OFF -DENABLE_STATIC_ZLIB=OFF -DENABLE_STATIC_CAPSIMAGE=OFF

# Nintendo Wii
#libretro-build-wii:
#  extends:
#    - .libretro-wii-static-cmake-retroarch-master
#    - .core-defs
#  image: $CI_SERVER_HOST:5050/libretro-infrastructure/libretro-build-devkitpro:20260903
#  variables:
#    CORE_ARGS: -DENABLE_LIBRETRO=ON -DENABLE_HATARI=OFF -DENABLE_TOOLS=OFF -DENABLE_STATIC_ZLIB=OFF -DENABLE_STATIC_CAPSIMAGE=OFF

# Nintendo WiiU
libretro-build-wiiu:
  extends:
    - .libretro-wiiu-static-cmake-retroarch-master
    - .core-defs
  variables:
    CORE_ARGS: -DENABLE_LIBRETRO=ON -DENABLE_HATARI=OFF -DENABLE_TOOLS=OFF -DENABLE_STATIC_ZLIB=OFF -DENABLE_STATIC_CAPSIMAGE=OFF

#################################### MISC ####################################
# webOS 32-bit
libretro-build-webos-armv7a:
  extends:
    - .libretro-webos-armv7a-cmake
    - .core-defs
