name: "Bug report"
description: Report a problem with the libretro port of Hatari
title: "[Bug]: "
labels: [bug]
body:
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you running on?
      options:
        - Android
        - iOS
        - iPadOS
        - Linux
        - macOS
        - tvOS
        - webOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: Provide a clear and detailed description of the problem
    validations:
      required: true

  - type: textarea
    id: log_output
    attributes:
      label: Log Output
      description: |
        Paste relevant log output here (use code blocks if possible). Logs are not optional!
        See [RetroArch.com](https://docs.libretro.com/guides/generating-retroarch-logs/) on how to make a log.
        Use [Pastebin](https://pastebin.com/) / [Gist](https://gist.github.com/) for larger logs.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Note:** Please first check existing issues before creating a new one.  
