name: Build Hatari (libretro) on macOS

on: [push, pull_request]

env:
  core_id: hatari_libretro

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: "macOS x64"
          os: macos-latest
          ZIP_NAME_SUFFIX: macos_x64
    steps:
    - name: Install dependencies
      run: |
        brew update
        brew install cmake \
          mbedtls sdl2 zlib

    - name: Checkout Hatari (libretro) repo
      uses: actions/checkout@v7
      with:
        path: ${{ env.core_id }}
        submodules: recursive

    - name: Configure
      run: |
        cd ${{ env.core_id }}
        mkdir -p build && cd build
        cmake .. \
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
          -DENABLE_LIBRETRO=ON -DENABLE_HATARI=OFF -DENABLE_TOOLS=OFF -DENABLE_STATIC_ZLIB=ON -DENABLE_STATIC_CAPSIMAGE=ON \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install

    - name: Build
      run: |
        cd ${{ env.core_id }}/build
        make -j$(sysctl -n hw.ncpu)
